const actionType = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  SET_PROFILE: "SET_PROFILE",
  REFRESH_TOKEN: "REFRESH_TOKEN",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAILURE",

  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",

  GET_PRODUCTS_BY_CATEGORY_REQUEST: "GET_PRODUCTS_BY_CATEGORY_REQUEST",
  GET_PRODUCTS_BY_CATEGORY_SUCCESS: "GET_PRODUCTS_BY_CATEGORY_SUCCESS",
  GET_PRODUCTS_BY_CATEGORY_FAILURE: "GET_PRODUCTS_BY_CATEGORY_FAILURE",

  GET_PRODUCT_DETAIL_REQUEST: "GET_PRODUCT_DETAIL_REQUEST",
  GET_PRODUCT_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
  GET_PRODUCT_DETAIL_FAILURE: "GET_PRODUCT_DETAIL_FAILURE",

  GET_CAROUSEL_REQUEST: "GET_CAROUSEL_REQUEST",
  GET_CAROUSEL_SUCCESS: "GET_CAROUSEL_SUCCESS",
  GET_CAROUSEL_FAILURE: "GET_CAROUSEL_FAILURE",

  GET_COURT_REQUEST: "GET_COURT_REQUEST",
  GET_COURT_SUCCESS: "GET_COURT_SUCCESS",
  GET_COURT_FAILURE: "GET_COURT_FAILURE",

  GET_DETAIL_COURT_REQUEST: "GET_COURT_DETAIL_REQUEST",
  GET_DETAIL_COURT_SUCCESS: "GET_COURT_DETAIL_SUCCESS",
  GET_DETAIL_COURT_FAILURE: "GET_COURT_DETAIL_FAILURE",

  GET_TOURNAMENT_REQUEST: "GET_TOURNAMENT_REQUEST",
  GET_TOURNAMENT_SUCCESS: "GET_TOURNAMENT_SUCCESS",
  GET_TOURNAMENT_FAILURE: "GET_TOURNAMENT_FAILURE",

  GET_TOURNAMENT_DETAIL_REQUEST: "GET_TOURNAMENT_DETAIL_REQUEST",
  GET_TOURNAMENT_DETAIL_SUCCESS: "GET_TOURNAMENT_DETAIL_SUCCESS",
  GET_TOURNAMENT_DETAIL_FAILURE: "GET_TOURNAMENT_DETAIL_FAILURE",

  GET_ALL_USERS_REQUEST: "GET_ALL_USERS_REQUEST",
  GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAILURE: "GET_ALL_USERS_FAILURE",

  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAILURE: "GET_CART_FAILURE",

  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

  GET_ONE_USER_REQUEST: "GET_ONE_USER_REQUEST",
  GET_ONE_USER_SUCCESS: "GET_ONE_USER_SUCCESS",
  GET_ONE_USER_FAILURE: "GET_ONE_USER_FAILURE",

  GET_SUPPORT_REQUEST: "GET_SUPPORT_REQUEST",
  GET_SUPPORT_SUCCESS: "GET_SUPPORT_SUCCESS",
  GET_SUPPORT_FAILURE: "GET_SUPPORT_FAILURE",

  GET_CATEGORIES_REQUEST: "GET_CATEGORIES_REQUEST",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",

  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",

  GET_PRICES_REQUEST: "GET_PRICES_REQUEST",
  GET_PRICES_SUCCESS: "GET_PRICES_SUCCESS",
  GET_PRICES_FAILURE: "GET_PRICES_FAILURE",

  GET_USER_LOCKED_REQUEST: "GET_USER_LOCKED_REQUEST",
  GET_USER_LOCKED_SUCCESS: "GET_USER_LOCKED_SUCCESS",
  GET_USER_LOCKED_FAILURE: "GET_USER_LOCKED_FAILURE",

  GET_ALL_SPORTS_REQUEST: "GET_ALL_SPORTS_REQUEST",
  GET_ALL_SPORTS_SUCCESS: "GET_ALL_SPORTS_SUCCESS",
  GET_ALL_SPORTS_FAILURE: "GET_ALL_SPORTS_FAILURE",

  GET_ALL_COURTTYPES_REQUEST: "GET_ALL_COURTTYPES_REQUEST",
  GET_ALL_COURTTYPES_SUCCESS: "GET_ALL_COURTTYPES_SUCCESS",
  GET_ALL_COURTTYPES_FAILURE: "GET_ALL_COURTTYPES_FAILURE",
};

export default actionType;