const actionType = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  SET_PROFILE: "SET_PROFILE",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  GOOGLE_LOGIN_REQUEST: "GOOGLE_LOGIN_REQUEST",
  GOOGLE_LOGIN_SUCCESS: "GOOGLE_LOGIN_SUCCESS",
  GOOGLE_LOGIN_FAILURE: "GOOGLE_LOGIN_FAILURE",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAILURE",

  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",

  GET_PRODUCTS_BY_CATEGORY_REQUEST: "GET_PRODUCTS_BY_CATEGORY_REQUEST",
  GET_PRODUCTS_BY_CATEGORY_SUCCESS: "GET_PRODUCTS_BY_CATEGORY_SUCCESS",
  GET_PRODUCTS_BY_CATEGORY_FAILURE: "GET_PRODUCTS_BY_CATEGORY_FAILURE",

  GET_PRODUCT_DETAIL_REQUEST: "GET_PRODUCT_DETAIL_REQUEST",
  GET_PRODUCT_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
  GET_PRODUCT_DETAIL_FAILURE: "GET_PRODUCT_DETAIL_FAILURE",

  GET_CAROUSEL_REQUEST: "GET_CAROUSEL_REQUEST",
  GET_CAROUSEL_SUCCESS: "GET_CAROUSEL_SUCCESS",
  GET_CAROUSEL_FAILURE: "GET_CAROUSEL_FAILURE",

  GET_COURT_REQUEST: "GET_COURT_REQUEST",
  GET_COURT_SUCCESS: "GET_COURT_SUCCESS",
  GET_COURT_FAILURE: "GET_COURT_FAILURE",

  GET_DETAIL_COURT_REQUEST: "GET_COURT_DETAIL_REQUEST",
  GET_DETAIL_COURT_SUCCESS: "GET_COURT_DETAIL_SUCCESS",
  GET_DETAIL_COURT_FAILURE: "GET_COURT_DETAIL_FAILURE",
};

export default actionType;