import {default as Admin} from './Admin.tsx'
import {default as AdminUsers} from './AdminUsers.tsx'
import {default as AdminTournaments} from './AdminTournaments.tsx'
import {default as AdminCourts} from './AdminCourts.tsx'
import {default as Dashboard} from './Dashboard.tsx'
import {default as Support} from './Support.tsx'
import {default as AdminProducts} from './AdminProducts.tsx'
import {default as AdminCategories} from './AdminCategories.tsx'
import {default as AdminPrice} from './AdminPrice.tsx'
import {default as AdminCarosel} from './AdminCarosel.tsx'
import {default as LockedUser} from './LockedUser.tsx'
import {default as AdminBooking} from './AdminBooking.tsx'
// import {default as AdminChats} from './AdminChats.tsx'